"use client";

// import type { Metadata } from "next";
import "./globals.css";

import MobileOnly from "@/components/mobile-only";

// export const metadata: Metadata = {
//     title: "FarmChain",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <MobileOnly>{children}</MobileOnly>
            </body>
        </html>
    );
}
